import { LevelConfig } from "../level-manager";

export const buildings: LevelConfig["decorations"] = [
  // ### Right 1 ### (15, 0, -30) -> (135, 0, -150)
  {
    type: "model",
    modelPath: "building/building_1.usdz",
    position: [68, 0.3, -90],
    targetSizeY: 120,
    rotation: [0, 0, 0],
    solid: true,
    doubleSided: true,
  },

  // ### Left 1 ### (-15, 0, -30) -> (-135, 0, -150)
  // Row 1 (Deep Z):
  {
    type: "model",
    modelPath: "building/downtown_buildings.usdz",
    position: [-110.5, 0, -125.5],
    rotation: [0, 0, 0],
    childIndex: 11,
    solid: true,
    doubleSided: true,
  },
  {
    type: "model",
    modelPath: "building/downtown_buildings.usdz",
    position: [-70, 0, -127],
    rotation: [0, 0, 0],
    childIndex: 14,
    solid: true,
    doubleSided: true,
  },
  {
    type: "model",
    modelPath: "building/downtown_buildings.usdz",
    position: [-35, 0, -133],
    rotation: [0, 0, 0],
    childIndex: 8,
    solid: true,
    doubleSided: true,
  },
  // Row 2 (Middle Z):
  {
    type: "model",
    modelPath: "building/downtown_buildings.usdz",
    position: [-110.5, 0, -86],
    rotation: [0, 0, 0],
    childIndex: 4,
    solid: true,
    doubleSided: true,
  },
  {
    type: "model",
    modelPath: "building/downtown_buildings.usdz",
    position: [-69.5, 0, -86.5],
    rotation: [0, 0, 0],
    childIndex: 16,
    solid: true,
    doubleSided: true,
  },
  {
    type: "model",
    modelPath: "building/downtown_buildings.usdz",
    position: [-32, 0, -93],
    rotation: [0, 0, 0],
    childIndex: 7,
    solid: true,
    doubleSided: true,
  },
  // Row 3 (Close Z):
  {
    type: "model",
    modelPath: "building/downtown_buildings.usdz",
    position: [-117.5, 0, -50],
    rotation: [0, 0, 0],
    childIndex: 2,
    solid: true,
    doubleSided: true,
  },
  {
    type: "model",
    modelPath: "building/downtown_buildings.usdz",
    position: [-82, 0, -48],
    rotation: [0, 0, 0],
    childIndex: 13,
    solid: true,
    doubleSided: true,
  },
  {
    type: "model",
    modelPath: "building/downtown_buildings.usdz",
    position: [-44, 0, -49],
    rotation: [0, 0, 0],
    childIndex: 6,
    solid: true,
    doubleSided: true,
  },

  // ### Left 2 ### (-15, 0, -180) -> (-135, 0, -300)
  // Row 1 (Deep Z):
  {
    type: "model",
    modelPath: "building/downtown_buildings.usdz",
    position: [-101.5, 0, -274.5],
    rotation: [0, 0, 0],
    childIndex: 5,
    solid: true,
    doubleSided: true,
  },
  {
    type: "model",
    modelPath: "building/downtown_buildings.usdz",
    position: [-52, 0, -279],
    rotation: [0, 0, 0],
    childIndex: 15,
    solid: true,
    doubleSided: true,
  },
  {
    type: "model",
    modelPath: "building/downtown_buildings.usdz",
    position: [-22.5, 0, -275],
    rotation: [0, 0, 0],
    childIndex: 2,
    solid: true,
    doubleSided: true,
  },
  // Row 2 (Middle Z):
  {
    type: "model",
    modelPath: "building/downtown_buildings.usdz",
    position: [-112, 0, -231],
    rotation: [0, 0, 0],
    childIndex: 12,
    solid: true,
    doubleSided: true,
  },
  {
    type: "model",
    modelPath: "building/downtown_buildings.usdz",
    position: [-70, 0, -231],
    rotation: [0, 0, 0],
    childIndex: 4,
    solid: true,
    doubleSided: true,
  },
  {
    type: "model",
    modelPath: "building/downtown_buildings.usdz",
    position: [-33, 0, -231],
    rotation: [0, 0, 0],
    childIndex: 14,
    solid: true,
    doubleSided: true,
  },
  // Row 3 (Close Z):
  {
    type: "model",
    modelPath: "building/downtown_buildings.usdz",
    position: [-112, 0, -198],
    rotation: [0, 0, 0],
    childIndex: 13,
    solid: true,
    doubleSided: true,
  },
  {
    type: "model",
    modelPath: "building/downtown_buildings.usdz",
    position: [-70, 0, -192],
    rotation: [0, 0, 0],
    childIndex: 7,
    solid: true,
    doubleSided: true,
  },
  {
    type: "model",
    modelPath: "building/downtown_buildings.usdz",
    position: [-33, 0, -192],
    rotation: [0, 0, 0],
    childIndex: 8,
    solid: true,
    doubleSided: true,
  },

  // ### Right 2 ### (15, 0, -180) -> (135, 0, -300)
  // Row 1 (Deep Z):
  {
    type: "model",
    modelPath: "building/downtown_buildings.usdz",
    position: [35, 0, -275],
    rotation: [0, 0, 0],
    childIndex: 12,
    solid: true,
    doubleSided: true,
  },
  {
    type: "model",
    modelPath: "building/downtown_buildings.usdz",
    position: [78, 0, -275],
    rotation: [0, 0, 0],
    childIndex: 4,
    solid: true,
    doubleSided: true,
  },
  {
    type: "model",
    modelPath: "building/downtown_buildings.usdz",
    position: [130, 0, -270],
    rotation: [0, Math.PI / 3, 0],
    childIndex: 5,
    solid: true,
    doubleSided: true,
  },
  // Row 2 (Middle Z):
  {
    type: "model",
    modelPath: "building/downtown_buildings.usdz",
    position: [36.5, 0, -235],
    rotation: [0, 0, 0],
    childIndex: 11,
    solid: true,
    doubleSided: true,
  },
  {
    type: "model",
    modelPath: "building/downtown_buildings.usdz",
    position: [83, 0, -230],
    rotation: [0, 0, 0],
    childIndex: 13,
    solid: true,
    doubleSided: true,
  },
  {
    type: "model",
    modelPath: "building/downtown_buildings.usdz",
    position: [124, 0, -210],
    rotation: [0, Math.PI / 2, 0],
    childIndex: 1,
    solid: true,
    doubleSided: true,
  },
  // Row 3 (Close Z):
  {
    type: "model",
    modelPath: "building/downtown_buildings.usdz",
    position: [33, 0, -196],
    rotation: [0, 0, 0],
    childIndex: 15,
    solid: true,
    doubleSided: true,
  },
  {
    type: "model",
    modelPath: "building/downtown_buildings.usdz",
    position: [65, 0, -192],
    rotation: [0, 0, 0],
    childIndex: 7,
    solid: true,
    doubleSided: true,
  },
  {
    type: "model",
    modelPath: "building/downtown_buildings.usdz",
    position: [95, 0, -192],
    rotation: [0, 0, 0],
    childIndex: 8,
    solid: true,
    doubleSided: true,
  },
];
