import { LevelConfig } from "../level-manager";

export const houses: LevelConfig["decorations"] = [
  {
    type: "model",
    modelPath: "/assets/models/barn_1.usdz",
    position: [-50, 0, -10],
    scale: [0.05, 0.05, 0.05],
    rotation: [0, 0.2, 0],
    solid: true,
  },
  {
    type: "model",
    modelPath: "/assets/models/barn_2.usdz",
    position: [-50, 0, -28],
    scale: [0.05, 0.05, 0.05],
    rotation: [0, -0.4, 0],
    solid: true,
  },
  {
    type: "model",
    modelPath: "/assets/models/barn_3.usdz",
    position: [-50, 0, -82],
    scale: [0.1, 0.1, 0.1],
    rotation: [0, -0.3, 0],
    solid: true,
  },
  {
    type: "model",
    modelPath: "/assets/models/barn_1.usdz",
    position: [-50, 0, -115],
    scale: [0.05, 0.05, 0.05],
    rotation: [0, 0.5, 0],
    solid: true,
  },
  {
    type: "model",
    modelPath: "/assets/models/barn_2.usdz",
    position: [-50, 0, -150],
    scale: [0.05, 0.05, 0.05],
    rotation: [0, -0.7, 0],
    solid: true,
  },
  {
    type: "model",
    modelPath: "/assets/models/barn_3.usdz",
    position: [48, 0, -32],
    scale: [0.1, 0.1, 0.1],
    rotation: [0, 0.4, 0],
    solid: true,
  },
  {
    type: "model",
    modelPath: "/assets/models/barn_1.usdz",
    position: [48, 0, -60],
    scale: [0.05, 0.05, 0.05],
    rotation: [0, -0.5, 0],
    solid: true,
  },
  {
    type: "model",
    modelPath: "/assets/models/barn_2.usdz",
    position: [48, 0, -100],
    scale: [0.05, 0.05, 0.05],
    rotation: [0, 0.3, 0],
    solid: true,
  },
  {
    type: "model",
    modelPath: "/assets/models/barn_3.usdz",
    position: [48, 0, -150],
    scale: [0.1, 0.1, 0.1],
    rotation: [0, 0.1, 0],
    solid: true,
  },
];
