import { LevelConfig } from "../level-manager";

const roadBlockSize: [number, number, number] = [30, 30, 1.0];

export const scene: LevelConfig["decorations"] = [
  // 0: straight road, 1: crossroad, 2: cut-off, 3: T-junction
  // ### Center 1 ###
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [15, 0, -15],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, Math.PI / 2],
    childIndex: 3,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [15, 0, -45],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, Math.PI / 2],
    childIndex: 0,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [15, 0, -75],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, Math.PI / 2],
    childIndex: 0,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [15, 0, -105],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, Math.PI / 2],
    childIndex: 0,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [15, 0, -135],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, Math.PI / 2],
    childIndex: 0,
    solid: true,
  },
  // ### Right 1 ###
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [30, 0, 0],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, 0],
    childIndex: 0,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [60, 0, 0],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, 0],
    childIndex: 0,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [90, 0, 0],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, 0],
    childIndex: 0,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [120, 0, 0],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, 0],
    childIndex: 0,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [150, 0, -30],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, Math.PI],
    childIndex: 2,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [165, 0, -45],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, Math.PI / 2],
    childIndex: 0,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [165, 0, -75],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, Math.PI / 2],
    childIndex: 0,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [165, 0, -105],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, Math.PI / 2],
    childIndex: 0,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [165, 0, -135],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, Math.PI / 2],
    childIndex: 0,
    solid: true,
  },
  // ### Left 1 ###
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [-30, 0, 0],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, 0],
    childIndex: 0,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [-60, 0, 0],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, 0],
    childIndex: 0,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [-90, 0, 0],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, 0],
    childIndex: 0,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [-120, 0, 0],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, 0],
    childIndex: 0,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [-135, 0, -15],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, Math.PI / 2],
    childIndex: 2,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [-135, 0, -45],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, Math.PI / 2],
    childIndex: 0,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [-135, 0, -75],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, Math.PI / 2],
    childIndex: 0,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [-135, 0, -105],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, Math.PI / 2],
    childIndex: 0,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [-135, 0, -135],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, Math.PI / 2],
    childIndex: 0,
    solid: true,
  },
  // ### Center 2 ###
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [0, 0, -150],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, 0],
    childIndex: 1,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [15, 0, -195],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, Math.PI / 2],
    childIndex: 0,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [15, 0, -225],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, Math.PI / 2],
    childIndex: 0,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [15, 0, -255],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, Math.PI / 2],
    childIndex: 0,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [15, 0, -285],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, Math.PI / 2],
    childIndex: 0,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [-15, 0, -315],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, -Math.PI / 2],
    childIndex: 3,
    solid: true,
  },
  // ### Right 2 ###
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [30, 0, -150],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, 0],
    childIndex: 0,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [60, 0, -150],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, 0],
    childIndex: 0,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [90, 0, -150],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, 0],
    childIndex: 0,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [120, 0, -150],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, 0],
    childIndex: 0,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [150, 0, -180],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, Math.PI],
    childIndex: 3,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [165, 0, -195],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, Math.PI / 2],
    childIndex: 0,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [165, 0, -225],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, Math.PI / 2],
    childIndex: 0,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [165, 0, -255],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, Math.PI / 2],
    childIndex: 0,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [165, 0, -285],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, Math.PI / 2],
    childIndex: 0,
    solid: true,
  },
  // ### Left 2 ###
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [-30, 0, -150],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, 0],
    childIndex: 0,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [-60, 0, -150],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, 0],
    childIndex: 0,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [-90, 0, -150],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, 0],
    childIndex: 0,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [-120, 0, -150],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, 0],
    childIndex: 0,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [-150, 0, -150],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, 0],
    childIndex: 3,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [-135, 0, -195],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, Math.PI / 2],
    childIndex: 0,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [-135, 0, -225],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, Math.PI / 2],
    childIndex: 0,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [-135, 0, -255],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, Math.PI / 2],
    childIndex: 0,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [-135, 0, -285],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, Math.PI / 2],
    childIndex: 0,
    solid: true,
  },
  // ### Right 3 ###
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [30, 0, -300],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, 0],
    childIndex: 0,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [60, 0, -300],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, 0],
    childIndex: 0,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [90, 0, -300],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, 0],
    childIndex: 0,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [120, 0, -300],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, 0],
    childIndex: 0,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [135, 0, -315],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, -Math.PI / 2],
    childIndex: 2,
    solid: true,
  },
  // ### Left 3 ###
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [-30, 0, -300],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, 0],
    childIndex: 0,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [-60, 0, -300],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, 0],
    childIndex: 0,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [-90, 0, -300],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, 0],
    childIndex: 0,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [-120, 0, -300],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, 0],
    childIndex: 0,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/roads.usdz",
    position: [-150, 0, -300],
    targetSize: roadBlockSize,
    rotation: [-Math.PI / 2, 0, 0],
    childIndex: 2,
    solid: true,
  },
];
