import { LevelConfig } from "../level-manager";

export const trees: LevelConfig["decorations"] = [
  // === LOW POLY TREES — mỗi entry dùng 1 cây con riêng (childIndex) ===
  // File low_poly_tree.usdz chứa nhiều cây → childIndex chọn từng cây lẻ
  // Scale 0.05 (lớn hơn cũ ~4x). Nếu cây quá to/nhỏ hãy báo để điều chỉnh.
  {
    type: "model",
    modelPath: "/assets/models/tree/low_poly_tree.usdz",
    position: [-25, 0, -2],
    scale: [2, 2, 2],
    rotation: [0, 0.3, 0],
    childIndex: 0,
  },
  {
    type: "model",
    modelPath: "/assets/models/tree/low_poly_tree.usdz",
    position: [-15, 0, -2],
    scale: [2, 2, 2],
    rotation: [0, 0.8, 0],
    childIndex: 1,
  },
  {
    type: "model",
    modelPath: "/assets/models/tree/low_poly_tree.usdz",
    position: [-16, 0, -2],
    scale: [2, 2, 2],
    rotation: [0, 1.5, 0],
    childIndex: 2,
  },
  {
    type: "model",
    modelPath: "/assets/models/tree/low_poly_tree.usdz",
    position: [-0, 0, -1],
    scale: [2, 2, 2],
    rotation: [0, 0.5, 0],
    childIndex: 3,
  },
  {
    type: "model",
    modelPath: "/assets/models/tree/low_poly_tree.usdz",
    position: [22, 0, -20],
    scale: [2, 2, 2],
    rotation: [0, 1.2, 0],
    childIndex: 4,
  },
  {
    type: "model",
    modelPath: "/assets/models/tree/low_poly_tree.usdz",
    position: [-28, 0, -35],
    scale: [2, 2, 2],
    rotation: [0, 2.0, 0],
    childIndex: 0,
  },
  {
    type: "model",
    modelPath: "/assets/models/tree/low_poly_tree.usdz",
    position: [30, 0, -50],
    scale: [2, 2, 2],
    rotation: [0, 0.7, 0],
    childIndex: 1,
  },
  {
    type: "model",
    modelPath: "/assets/models/tree/low_poly_tree.usdz",
    position: [-25, 0, -68],
    scale: [2, 2, 2],
    rotation: [0, 1.8, 0],
    childIndex: 2,
  },
  {
    type: "model",
    modelPath: "/assets/models/tree/low_poly_tree.usdz",
    position: [28, 0, -82],
    scale: [2, 2, 2],
    rotation: [0, 0.4, 0],
    childIndex: 3,
  },
  {
    type: "model",
    modelPath: "/assets/models/tree/low_poly_tree.usdz",
    position: [-22, 0, -100],
    scale: [2, 2, 2],
    rotation: [0, 2.5, 0],
    childIndex: 4,
  },
  {
    type: "model",
    modelPath: "/assets/models/tree/low_poly_tree.usdz",
    position: [32, 0, -120],
    scale: [2, 2, 2],
    rotation: [0, 0.9, 0],
    childIndex: 0,
  },
  {
    type: "model",
    modelPath: "/assets/models/tree/low_poly_tree.usdz",
    position: [-18, 0, -138],
    scale: [2, 2, 2],
    rotation: [0, 1.4, 0],
    childIndex: 1,
  },
];
