import { LevelConfig } from "../level-manager";

export const trees: LevelConfig["decorations"] = [
  {
    type: "model",
    modelPath: "scene/trees.usdz",
    position: [-25, 0, -2],
    scale: [0.1, 0.1, 0.1],
    rotation: [0, 0.3, 0],
    childIndex: 1,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/trees.usdz",
    position: [-15, 0, -2],
    scale: [0.1, 0.1, 0.1],
    rotation: [0, 0.8, 0],
    childIndex: 2,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/trees.usdz",
    position: [-16, 0, -2],
    scale: [0.1, 0.1, 0.1],
    rotation: [0, 1.5, 0],
    childIndex: 3,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/trees.usdz",
    position: [10, 0, 10],
    scale: [0.1, 0.1, 0.1],
    rotation: [0, 0.5, 0],
    childIndex: 4,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/trees.usdz",
    position: [22, 0, -20],
    scale: [0.1, 0.1, 0.1],
    rotation: [0, 1.2, 0],
    childIndex: 5,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/trees.usdz",
    position: [-28, -1, -35],
    scale: [0.1, 0.1, 0.1],
    rotation: [0, 2.0, 0],
    childIndex: 6,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/trees.usdz",
    position: [30, -2, -50],
    scale: [0.1, 0.1, 0.1],
    rotation: [0, 0.7, 0],
    childIndex: 7,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/trees.usdz",
    position: [-25, 0, -68],
    scale: [0.1, 0.1, 0.1],
    rotation: [0, 1.8, 0],
    childIndex: 8,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/trees.usdz",
    position: [28, 0, -82],
    scale: [0.1, 0.1, 0.1],
    rotation: [0, 0.4, 0],
    childIndex: 9,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/trees.usdz",
    position: [-22, -1, -100],
    scale: [0.1, 0.1, 0.1],
    rotation: [0, 2.5, 0],
    childIndex: 10,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/trees.usdz",
    position: [32, 0, -120],
    scale: [0.1, 0.1, 0.1],
    rotation: [0, 0.9, 0],
    childIndex: 11,
    solid: true,
  },
  {
    type: "model",
    modelPath: "scene/trees.usdz",
    position: [-18, 0, -138],
    scale: [0.1, 0.1, 0.1],
    rotation: [0, 1.4, 0],
    childIndex: 12,
    solid: true,
  },
];
