import { LevelConfig } from "../level-manager";

export const trees: LevelConfig["decorations"] = [
  // === LOW POLY TREES ===
  // File low_poly_trees.usdz chứa nhiều cây → childIndex chọn từng cây lẻ
  {
    type: "model",
    modelPath: "/assets/models/scene/low_poly_trees.usdz",
    position: [-25, 0, -2],
    scale: [0.1, 0.1, 0.1],
    rotation: [0, 0.3, 0],
    childIndex: 1,
  },
  {
    type: "model",
    modelPath: "/assets/models/scene/low_poly_trees.usdz",
    position: [-15, 0, -2],
    scale: [0.1, 0.1, 0.1],
    rotation: [0, 0.8, 0],
    childIndex: 2,
  },
  {
    type: "model",
    modelPath: "/assets/models/scene/low_poly_trees.usdz",
    position: [-16, 0, -2],
    scale: [0.1, 0.1, 0.1],
    rotation: [0, 1.5, 0],
    childIndex: 3,
  },
  {
    type: "model",
    modelPath: "/assets/models/scene/low_poly_trees.usdz",
    position: [-0, 0, -1],
    scale: [0.1, 0.1, 0.1],
    rotation: [0, 0.5, 0],
    childIndex: 4,
  },
  {
    type: "model",
    modelPath: "/assets/models/scene/low_poly_trees.usdz",
    position: [22, 0, -20],
    scale: [0.1, 0.1, 0.1],
    rotation: [0, 1.2, 0],
    childIndex: 5,
  },
  {
    type: "model",
    modelPath: "/assets/models/scene/low_poly_trees.usdz",
    position: [-28, -3, -35],
    scale: [0.1, 0.1, 0.1],
    rotation: [0, 2.0, 0],
    childIndex: 6,
  },
  {
    type: "model",
    modelPath: "/assets/models/scene/low_poly_trees.usdz",
    position: [30, -3, -50],
    scale: [0.1, 0.1, 0.1],
    rotation: [0, 0.7, 0],
    childIndex: 7,
  },
  {
    type: "model",
    modelPath: "/assets/models/scene/low_poly_trees.usdz",
    position: [-25, 0, -68],
    scale: [0.1, 0.1, 0.1],
    rotation: [0, 1.8, 0],
    childIndex: 8,
  },
  {
    type: "model",
    modelPath: "/assets/models/scene/low_poly_trees.usdz",
    position: [28, 0, -82],
    scale: [0.1, 0.1, 0.1],
    rotation: [0, 0.4, 0],
    childIndex: 9,
  },
  {
    type: "model",
    modelPath: "/assets/models/scene/low_poly_trees.usdz",
    position: [-22, -3, -100],
    scale: [0.1, 0.1, 0.1],
    rotation: [0, 2.5, 0],
    childIndex: 10,
  },
  {
    type: "model",
    modelPath: "/assets/models/scene/low_poly_trees.usdz",
    position: [32, 0, -120],
    scale: [0.1, 0.1, 0.1],
    rotation: [0, 0.9, 0],
    childIndex: 11,
  },
  {
    type: "model",
    modelPath: "/assets/models/scene/low_poly_trees.usdz",
    position: [-18, 0, -138],
    scale: [0.1, 0.1, 0.1],
    rotation: [0, 1.4, 0],
    childIndex: 12,
  },
];
